framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            assets/: ''
            vendor/symfony/ux-toolkit/kits/: '@symfony/ux-toolkit/kits'
        excluded_patterns:
            - '*/assets/styles/_*.scss'
            - '*/assets/styles/**/_*.scss'
            - '*/assets/icons/**'
            - '*/assets/react/build**'     # React build dir
            - '*/assets/react/src**'       # React sources
            - '*/assets/svelte/build**'    # ESvelte build dir
            - '*/assets/svelte/src**'      # Svelte source files
            - '*/kits/**/*.html.twig'      # UX Toolkit kit Twig templates
            - '*/kits/**/*.md'             # UX Toolkit kit documentation
            - '*/kits/**/manifest.json'    # UX Toolkit kit manifest files
        importmap_polyfill: false

react:
    controllers_path: '%kernel.project_dir%/assets/react/dist/controllers'

svelte:
    controllers_path: '%kernel.project_dir%/assets/svelte/dist/controllers'
